version: 2.1

jobs:
  tfsec_tests:
    docker:
      - image: aquasec/tfsec:latest
    steps:
      - checkout
      - run:
          name: Run tfsec tests
          command: tfsec ./infrastructure

  terratest:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run: wget https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      - run: sudo unzip terraform_1.8.3_linux_amd64.zip -d /usr/local/bin
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/terragrunt_linux_amd64
      - run: cp terragrunt_linux_amd64 terragrunt
      - run: chmod u+x terragrunt
      - run: sudo mv terragrunt /usr/local/bin/terragrunt
      - run: go test -v ./terratests

workflows:
  test:
    jobs:
      - tfsec_tests
      - terratest