version: 2.1

jobs:
  tfsec_tests:
    docker:
      - image: aquasec/tfsec:latest
    steps:
      - checkout
      - run:
          name: Run tfsec tests
          command: tfsec ./infrastructure

  terratest:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform

      # Install Terragrunt
      - run: |
          curl -LJO https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
      - run: go test -v ./terratests

workflows:
  test:
    jobs:
      - tfsec_tests
      - terratest