version: 2.1

jobs:
  tfsec_tests:
    docker:
      - image: aquasec/tfsec:latest
    steps:
      - checkout
      - run:
          name: Run tfsec tests
          command: tfsec ./infrastructure

  terratest:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run: apt-get update && apt-get install -y unzip
      - run: wget https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      - run: unzip terraform_1.8.3_linux_amd64.zip -d /usr/local/bin
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/terragrunt_linux_amd64
      - run: cp terragrunt_linux_amd64 terragrunt
      - run: chmod u+x terragrunt
      - run: mv terragrunt /usr/local/bin/terragrunt
      - run: go mod init mymodule
      - run:
          name: Install dependencies
          command: |
            go get github.com/gruntwork-io/terratest/modules/aws
            go get github.com/gruntwork-io/terratest/modules/terraform
            go get github.com/stretchr/testify/assert
            go mod tidy
      - run: go test -v ./terratests/test

workflows:
  test:
    jobs:
      - tfsec_tests
      - terratest