apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tf-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/bugaenkoyu/webserver-ec2-module-terraform
  ref:
    branch: main
  secretRef:
    name: flux-token
  